### ISSUE TITLE
Mocha.prototype.run is not executing

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-protractor#5]
This code is not being executed:
https://github.com/digitalbazaar/bedrock-protractor/blob/master/lib/helper.js#L42

Which is causing a failure here because self.mocha has not been set:
https://github.com/digitalbazaar/bedrock-protractor/blob/master/lib/helper.js#L230

This failure occurs when attempting to run the protractor tests in bedrock-idp.  bedrock-angular-resolver adds its unit tests first via: https://github.com/digitalbazaar/bedrock-angular-resolver/blob/master/bedrock/config.js

**Comment by dlongley** [comment]
Fixed by d01f3a7602d2f0daee9a3819fbc3b8c7e1489bcb and a391de2b019332be73b2ff6158dc26ca86a5ef18.
